#NumPy Practise
NumPy에 대해서 공부하며 기록하기 위하여  작성하였습니다.   
영상은 https://youtu.be/xECXZ3tyONo 에서 참고했습니다 (영어).


#NumPy?
NumPy는 data science, machine learning 등을 하고 싶다면 필수적으로 알아야 할 파이썬 라이브러리입니다. 수를 다루는 라이브러리로, 파이썬에서 가장 강력한 라이브러리 중 하나입니다.       
가장 큰 특징으로는 빠르다는 것입니다. 엄청난 양의 수를 훨씬 빠르게 다룰 수 있습니다. 또, 효과적인 기능들도 많고요.

#Import
NumPy 는 아래와 같이 import 합니다.   
import numpy 만으로도 사용할 수 있지만, 파이썬 관행상 as np와 같이 간단하게 두 글자로 줄여서 사용합니다.

In [1]:
import numpy as np

#Arrays
NumPy에서 array를 선언하는 방법을 다룹니다.
np.zeros()를 사용하면, float 형태의 0으로 이루어진 array를 만들며, 그 크기는 괄호 안의 인자와 같습니다.

In [2]:
a = np.zeros(3)
print(a)
type(a)
type(a[0])

[0. 0. 0.]


numpy.float64

array 내부의 기본 형태는 float 형임을 확인할 수 있습니다.   
zeros를 다음과 같이 활용할 수 있습니다.

In [3]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

또, 만들어진 array의 형태를 shape를 통해 자유롭게 바꿀 수 있습니다.

In [4]:
z.shape = (10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

ones를 이용하면 모든 element가 1인 array를 생성할 수 있고,   
empty를 이용하면 빈 array를 생성할 수 있습니다.

In [5]:
z = np.ones(10)
print(z)
z = np.empty(3)
print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0.]


#Linspace
linspace는 주어진 숫자의 범위 내에서, 원소의 갯수를 지정하면 자동으로 array를 생성해 줍니다.

In [6]:
z = np.linspace(2,10,5) #from 2 to 10, with 5 elements
z

array([ 2.,  4.,  6.,  8., 10.])

실제로 linspace의 경우, 그래프를 그릴 때 x좌표를 지정하는 등의 용도로 사용하기도 합니다.   
마찬가지로, 내부의 elements의 data type는 float입니다.

In [7]:
type(z[1])

numpy.float64

#Array (이어서)
array를 생성하는 방법을 하나 더 다룹니다.

In [8]:
z = np.array([10,20])
z

array([10, 20])

고전적인 방법으로, 원하는 element를 직접 넣어서 생성할 수 있습니다.

In [9]:
type(z[1])

numpy.int64

직접 입력한 array의 element는 integer 형태를 가지네요.

In [10]:
a_list = [1,2,3,4,5,6,7]
z = np.array([a_list])
z

array([[1, 2, 3, 4, 5, 6, 7]])

list를 array에 넣는 것 역시 가능합니다.

In [11]:
type(z)

numpy.ndarray

numpy array 형식인 것을 확인할 수 있습니다.

2차원 list 역시 array 안에 담을 수 있습니다.

In [12]:
b_list = [[9,8,7,6,5,4,3],[1,2,3,4,5,6,7]]
z = np.array([b_list])
z

array([[[9, 8, 7, 6, 5, 4, 3],
        [1, 2, 3, 4, 5, 6, 7]]])

이 경우 역시 numpy array 형식인 것을 확인할 수 있습니다.

In [13]:
type(z)

numpy.ndarray

논외) jupyter notebook을 사용할 때,   
배열 z에 적용할 수 있는 특정 function을 검색하려면
z. 이후 tab 버튼을 누르면 볼 수 있습니다. (google colab에서는 동작하지 않습니다)   
또, ?z를 입력하면, z에 대한 자세한 document를 볼 수 있습니다.

In [14]:
z.shape

(1, 2, 7)

#Random
array를 random하게 생성할 수 있습니다.

In [15]:
np.random.seed(0)
z1 = np.random.randint(10, size=6)
z1

array([5, 0, 3, 3, 7, 9])

6개의 원소를 가진, 0~9 범위 이내의 정수형 element를 가지는 array를 생성했습니다.

array의 element를 다음과 같이 접근할 수 있습니다.

In [16]:
z1[0]

5

In [17]:
z1[0:2]

array([5, 0])

In [18]:
z1[-1]

9

첫 번째는 단순히 n번째 인자를 가리킵니다.   
두 번째는 n번째 인자로부터, m까지의 범위를 가리킵니다. 0번째 인자부터 총 2개를 가리키는 예시를 볼 수 있습니다.   
세 번째는 -1번째 인자를 가리키는데, error가 나지 않고, 5번째 인자, 즉 뒤에서 첫 번째 인자인 9를 가리키는 것을 볼 수 있습니다.
   
python의 기본 list와 매우 흡사한 모습을 보임을 알 수 있습니다.

#Photo Example
다음으로, 하나의 사진을 가지고 numpy를 이용해서 어떻게 다룰 수 있는지 예시를 들어 보이겠습니다.


In [19]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


추가) google colab에서 파일 디렉토리를 사용하려면,    
위와 같은 과정이 필요합니다.   
자세한 내용은 https://blog.naver.com/anne9/221798711142 를 참고해 주세요.
   
Google CoLab이 아닌 일반 jupyter notebook에서 실행하시는 경우에는 위 코드는 실행하지 않으시면 됩니다.


In [20]:
from skimage import io
photo = io.imread('/content/gdrive/My Drive/light_temple.png')
type(photo)

numpy.ndarray

skimage 라이브러리를 사용하여 이미지를 가져왔습니다.   
이미지 photo의 형태는 numpy array인 것을 확인할 수 있습니다.

In [21]:
photo.shape

(270, 480, 4)

photo의 크기 역시 확인할 수 있습니다.   
(마지막 인수는 잘 모르겠습니다. 참고한 영상에서는 colour image라서 3이라고 하네요.)

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(photo)

matplotlib 라이브러리를 이용하여, photo를 출력해 보았습니다.

In [ ]:
plt.imshow(photo[::-1])

row를 반전해 보았습니다. 같은 사진이 상하가 반전된 것을 확인할 수 있습니다.

In [ ]:
plt.imshow(photo[:,::-1])

이번에는 column을 반전해 보았습니다. 같은 사진이 좌우가 반전되었음을 확인할 수 있습니다.

In [ ]:
plt.imshow(photo[40:150, 100:300])

원하는 영역만 지정하여 출력한 결과입니다.

In [ ]:
plt.imshow(photo[::2,::2])

이번에는 사진 자체에는 큰 차이가 없어 보이지만, row와 column을 각각 반으로 줄였습니다.   
아래의 좌표를 보시면 사진의 크기가 줄어들었음을 확인할 수 있습니다.

#Mathematical Operation
이 numpy array에 수학적인 연산을 해 보겠습니다.

In [28]:
photo
photo_sin = np.sin(photo)
photo_sin

array([[[ 0.9893 ,  0.657  ,  0.5293 , -0.5063 ],
        [ 0.9893 ,  0.657  ,  0.5293 , -0.5063 ],
        [ 0.9893 ,  0.657  ,  0.5293 , -0.5063 ],
        ...,
        [ 0.9893 , -0.2793 ,  1.     , -0.5063 ],
        [ 0.9893 ,  0.657  ,  0.5293 , -0.5063 ],
        [ 0.9893 ,  0.657  ,  0.5293 , -0.5063 ]],

       [[ 0.9893 ,  0.657  , -0.4282 , -0.5063 ],
        [ 0.9893 ,  0.657  , -0.4282 , -0.5063 ],
        [ 0.9893 ,  0.657  , -0.4282 , -0.5063 ],
        ...,
        [ 0.9893 , -0.2793 ,  0.5293 , -0.5063 ],
        [ 0.9893 , -0.2793 , -0.4282 , -0.5063 ],
        [ 0.9893 ,  0.657  , -0.4282 , -0.5063 ]],

       [[ 0.9893 ,  0.657  , -0.4282 , -0.5063 ],
        [ 0.9893 ,  0.657  , -0.4282 , -0.5063 ],
        [ 0.9893 ,  0.657  , -0.4282 , -0.5063 ],
        ...,
        [ 0.9893 , -0.2793 , -0.4282 , -0.5063 ],
        [ 0.9893 , -0.2793 , -0.4282 , -0.5063 ],
        [ 0.9893 ,  0.657  , -0.4282 , -0.5063 ]],

       ...,

       [[-0.00885, -0.2625 , -0.09717, -0.

array의 모든 값에 sin을 취한 모습입니다.   
물론 사진의 모든 값에 sin을 취할 일은 잘 없지만, 사진이 아닌 방대한 양의 데이터라고 가정하면 유용하게 사용할 수 있습니다.   
혹시나 해서 해봤지만 sin을 취한 photo_sin은 이미지로써 출력이 안됩니다. ㅎㅎ


In [29]:
print(np.sum(photo)) #array의 값의 총합을 구한다.
print(np.prod(photo)) #array의 값의 곱을 구한다.
print(np.mean(photo)) #array의 mean (평균값)을 구한다.
print(np.std(photo)) #array의 standard deviation (표준 편차)를 구한다.
print(np.var(photo)) #array의 variance (분산)를 구한다.
print(np.min(photo)) #array의 min (최저값)을 구한다.
print(np.max(photo)) #array의 max (최대값)을 구한다.
print(np.argmin(photo)) #array의 argmin 값을 구한다.
print(np.argmax(photo)) #array의 argmax 값을 구한다.

81289218
0
156.8079050925926
89.86236875305897
8075.245317910749
0
255
35341
3


이 외에, 위처럼 다양한 수학적 연산을 할 수 있습니다.   
이의 최대 강점은 별다른 loop 등을 이용하지 않고도, 코드 단 한 줄로 방대한 양의 데이터에 대한 연산을 수행할 수 있다는 점입니다.

#Other Operations
이 외에도, numpy를 이용하여 array에 다른 연산을 할 수 있습니다.

In [30]:
z = np.array([1,2,3,4,5])
z < 3

array([ True,  True, False, False, False])

z의 각 element에 대해, 3과 크기를 비교하여 그 결과를 true 혹은 false로 각각 출력합니다.

In [31]:
z > 3

array([False, False, False,  True,  True])

반대 역시 잘 작동하는 것을 확인할 수 있습니다.

In [32]:
z[z>3]

array([4, 5])

array z의 element 중에서, 조건에 맞는 element만 출력합니다.   
위의 경우, 3보다 큰 element인 4와 5를 출력하는 것을 알 수 있습니다.

#Example
photo를 이용하여 numpy 연산을 실제로 이용하는 예를 다룹니다.

In [33]:
photo_masked = np.where(photo > 100,255,0)

photo에서,

*   100보다 큰 element를,
*   255의 값을 대입하며,
*   그렇지 않은 element는 값을 0으로 대체합니다.   





In [ ]:
plt.imshow(photo_masked)

그 결과입니다. 색상값이 많이 바뀌었음을 확인할 수 있습니다.

In [ ]:
photo_masked = np.where(photo > 200, 255, 0)
plt.imshow(photo_masked)

값을 바꿈에 따라, 결과 이미지의 색상 역시 변화하는 것을 확인할 수 있습니다.

#Operations Between Matrices
numpy를 이용하여, array 간의 연산을 할 수 있습니다.

In [36]:
a_array = np.array([1,2,3,4,5])
b_array = np.array([6,7,8,9,10])

In [37]:
a_array + b_array

array([ 7,  9, 11, 13, 15])

두 array 간의 합 연산이 가능합니다.

In [38]:
a_array + 30

array([31, 32, 33, 34, 35])

array의 모든 element에 특정 값을 더할 수 있습니다.

In [39]:
a_array * b_array

array([ 6, 14, 24, 36, 50])

두 array의 각 element끼리의 곱연산 또한 할 수 있습니다.

In [40]:
a_array * 10

array([10, 20, 30, 40, 50])

array의 각 element에 특정 값을 곱할 수 있습니다.

In [41]:
a_array @ b_array

130

a_array와 b_array 사이의 dot product를 수행하였습니다.   
즉, 각 element끼리 곱한 값의 총합을 구합니다.

In [ ]:
plt.imshow(photo[:,:,0].T)

Transpose 연산입니다.   
.T를 array(matrix) 뒤에 붙임으로써 가로와 세로를 서로 바꿀 수 있습니다 (transpose).

In [43]:
x = np.array([2,1,4,5,3])
np.sort(x)

array([1, 2, 3, 4, 5])

sort를 이용하면 array 내의 값들을 손쉽게 정렬할 수 있습니다.